### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by davizp** [conaryHernandez/nodejs-sandbox#1]
I tried to understand this project but is kind of confusion because I didn't found any documentation. If there is any update on this don't hesitate to let me know.

Thanks.

**Comment by conaryHernandez** [comment]
FKU

**Comment by conaryHernandez** [comment]
Hi @davizp This project was created for learning purposes. Maybe later we will add some documentation. Sorry for the inconvenience.

Regards,

Conary
